language: php

php:
    - 7.1
    - 7.2

install:
    - composer install

script:
    - composer run test:cs
    - composer run test:unit -- --coverage-clover coverage-clover.xml

after_success:
    - composer require --dev satooshi/php-coveralls:1.*
    - vendor/bin/coveralls -v --coverage_clover=coverage-clover.xml --json_path=json-path.json
